apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
data:
  admin-password: YWRtaW5hZG1pbg==
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: grafana
spec:
  template:
    metadata:
      labels:
        name: grafana
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      containers:
      - name: grafana
        image: grafana/grafana:6.1.3
        env:
        - { name: "GF_SECURITY_ADMIN_PASSWORD", valueFrom: { secretKeyRef: { name: "grafana-secret", key: "admin-password" }}}
        ports:
          - { containerPort: 3000, protocol: TCP }
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "500Mi"
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
        volumeMounts:
          - { name: tmp,           mountPath: "/tmp" }
          - { name: vartmp,        mountPath: "/var/tmp" }
          - { name: grafana-data,  mountPath: "/var/lib/grafana" }
      volumes:
        - { name: "tmp",           emptyDir: {} }
        - { name: "vartmp",        emptyDir: {} }
        - { name: "grafana-data",  emptyDir: {} }
  replicas: 1
  selector:
    matchLabels:
      name: grafana
