apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    name: influxdb
spec:
  ports:
    - { name: "influxdb", port: 80, targetPort: 8086 }
  selector:
    name: influxdb
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
type: Opaque
data:
  user-password: YWRtaW5hZG1pbg==
  admin-password: YWRtaW5hZG1pbg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  template:
    metadata:
      labels:
        name: influxdb
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      containers:
        - name: influxdb
          image: influxdb:1.7-alpine
          env:
            - { name: "INFLUXDB_USER",                         value: "user"                                                                          } 
            - { name: "INFLUXDB_USER_PASSWORD",                valueFrom: { secretKeyRef: { name: "influxdb-secret", key: "user-password"           } } }
            - { name: "INFLUXDB_DB"           ,                value: "kafka"                                                                           }
            - { name: "INFLUXDB_ADMIN_USER",                   value: "admin"                                                                           }
            - { name: "INFLUXDB_ADMIN_PASSWORD",               valueFrom: { secretKeyRef: { name: "influxdb-secret", key: "admin-password"          } } }
            - { name: "INFLUXDB_META_DIR",                     value: "/influxdbdata/meta"                                                              }
            - { name: "INFLUXDB_DATA_DIR",                     value: "/influxdbdata/data"                                                              }
            - { name: "INFLUXDB_DATA_WAL_DIR",                 value: "/influxdbdata/wal"                                                               }
            - { name: "INFLUXDB_REPORTING_DISABLED",           value: "true"                                                                            }
          ports:
            - { containerPort: 8086, protocol: TCP }
          resources:
            requests: { memory: "1Gi" }
            limits:   { memory: "1Gi" }
          readinessProbe:
            tcpSocket:
              port: 8086
          volumeMounts:
            - { name: tmp,           mountPath: "/tmp" }
            - { name: vartmp,        mountPath: "/var/tmp" }
            - { name: influxdb-data, mountPath: "/influxdbdata" }
      volumes:
        - { name: "tmp",           emptyDir: {} }
        - { name: "vartmp",        emptyDir: {} }
        - { name: "influxdb-data", emptyDir: {} }
  replicas: 1
  selector:
    matchLabels:
      name: influxdb